name: Build, Test, & Deploy to NuGet

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal  
      
    - name: Pack
      run: dotnet pack
      
    - name: Deploy
      env:
        API_KEY:  ${{secrets.NUGET_API_KEY}}
      run: dotnet nuget push "**/*.nupkg" -k $API_KEY -s https://api.nuget.org/v3/index.json